THUNDERBOLT/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', include('pages.urls')),
    path('users/', include('users.urls')), # new
    path('users/', include('django.contrib.auth.urls')), # new
    path('admin/', admin.site.urls),
    path('gamestore/', include('gamestore.urls', namespace="gamestore")),
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # socialauth

]

gamestore/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

app_name = 'gamestore'
urlpatterns = [
    path('', views.index, name='index'),
    path('developer/', views.developer_home, name='developer_home'),
    path('developer/statistics', views.developer_statistics, name='developer_statistics'),
    path('developer/upload', views.developer_upload, name='developer_upload'),
    path('developer/deletegame', views.developer_delete_game, name='developer_delete_game'),
    path('developer/updateval/', views.developer_update_gameval, name='developer_update_gameval'),
    path('developer/updated/', views.developer_update_game_completed, name='developer_update_game_completed'),
    path('player/', views.player_home, name='player_home'),
    path('player/gamelist/', views.player_available_gamelist, name='player_available_gamelist'),
    path('player/gamebillpayment/', views.bill_payment, name='player_bill_payment'),
    path('player/gameplay/', views.player_gameplay, name='player_gameplay'),
    path('player/gameplay_score/', views.player_gamescore, name='player_gamescore'),
    path('player/gameplay_state/', views.player_gamestate, name='player_gamestate'),
    path('player/gameplay_load/', views.player_gameload, name='player_gameload'),
]

pages/urls.py
# pages/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    url(r'^pages/privacy_policy/', views.Privacy.as_view(), name='privacy'),
]

gamestore/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
'''
class User(models.Model):
    name   = models.TextField()
    role   = models.PositiveSmallIntegerField()
    email  = models.EmailField()
'''

class Games(models.Model):
    name_of_the_game = models.TextField(max_length=140)
    url_of_the_game = models.TextField()
    price  = models.FloatField()
    date_added = models.DateField()
    time_added = models.TimeField()
    description = models.TextField()
    category = models.TextField()
    #userid = models.ForeignKey(User, on_delete=models.CASCADE, related_name='games_userid')
    userid = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE
    )

class Game_log(models.Model):
    status = models.PositiveSmallIntegerField()
    save_state = models.TextField()
    #userid = models.ForeignKey(User, on_delete=models.CASCADE, related_name='gamelog_userid')
    userid = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE
    )
    gameid = models.ForeignKey(Games, on_delete=models.CASCADE, related_name='gamelog_gameid')

class Game_Details(models.Model):
    score = models.FloatField()
    date = models.DateField()
    time = models.TimeField()
    #userid = models.ForeignKey(User, on_delete=models.CASCADE, related_name='gamedetails_userid')
    userid = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE
    )
    gameid = models.ForeignKey(Games, on_delete=models.CASCADE, related_name='gamedetails_gameid')

class Admin_log(models.Model):
    date_modified = models.DateField()
    time_modified = models.TimeField()
    price_updated  = models.FloatField()
    description_modified = models.TextField()
    category_modified = models.TextField()
    url_updated = models.TextField()
    #userid = models.ForeignKey(User, on_delete=models.CASCADE, related_name='adminlog_userid')
    userid = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE
    )
    gameid = models.ForeignKey(Games, on_delete=models.CASCADE, related_name='adminlog_gameid')

class Purchase(models.Model):
    date_purchased = models.DateField()
    time_purchased = models.TimeField()
    price_purchased  = models.FloatField()
    #userid = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purchase_userid')
    userid = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE
    )
    gameid = models.ForeignKey(Games, on_delete=models.CASCADE, related_name='purchase_gameid')

    class Meta:
        unique_together = (('userid', 'gameid'),)


class Purchase_log(models.Model):
    name_of_the_game = models.TextField(max_length=140)
    price = models.FloatField()
    userid = models.ForeignKey(
        'users.CustomUser',
        on_delete=models.CASCADE
    )

gamestore/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from urllib.request import urlopen
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Games, Purchase, Game_Details, Game_log, Admin_log, Purchase_log
from hashlib import md5
import datetime
from users.models import CustomUser
from django.urls import reverse_lazy
from django.views import generic
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .decorators import developer_required
from .decorators import player_required
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.contrib import messages
from django.db.models import Count, Sum
from django.views.generic import TemplateView

# Home page of our gamestore application
@login_required(login_url='login')
def index(request):
    if request.user.role == '1':
        return developer_home(request)
    elif request.user.role == '2':
        return player_home(request)

# This function is used to show all the game uploaded by developer.
@login_required(login_url='login')
@developer_required
def developer_home(request):
    sold_games = list()
    sold_count = 0
    profit = 0
    current_user = request.user
    userid = get_object_or_404(CustomUser, pk=current_user.id)
    request.session['developerid'] = userid.id # developer id is stored in session for later use
    if request.method == 'POST':
        # search by name and category
        search_game_name = request.POST.get('search')
        search_game_category = request.POST.get('category')
        if search_game_name:
            gamelist = Games.objects.filter(name_of_the_game__icontains = search_game_name,
                                            userid = current_user.id)
        elif search_game_category and search_game_category != "Select Category":
            gamelist = Games.objects.filter(category__icontains = search_game_category,
                                            userid = current_user.id)
        elif search_game_name and search_game_category:
            gamelist = Games.objects.filter(name_of_the_game__icontains = search_game_name,
                                            category__icontains = search_game_category,
                                            userid = current_user.id)
        else:
            gamelist =  Games.objects.filter(userid=current_user.id)

    else:
        gamelist = Games.objects.filter(userid=current_user.id)

    # for developer statistics
    sold_gamelist = Purchase_log.objects.filter(userid = current_user.id)
    # total uploaded game
    total_uploaded_games = Games.objects.filter(userid=current_user.id)
    game_count = len(total_uploaded_games)
    # total number of sold games and profit
    for game in sold_gamelist:
        sold_count += 1
        profit += game.price

    profit = round(profit, 2)
    context = {'dev_home':'Developer Home','gamelist':gamelist,'game_count':game_count,'profit':profit,'sold_count':sold_count,'developer_name':userid.username}
    return render(request,'gamestore/developer_home.html',context)


# Player home will show all the game he/she has already purchashed.
# when the game is purchased the checksum will be calculated.
# Checksum will be compared with the received one, if it matches then the player home page will be loaded.
@login_required(login_url='login')
@player_required
@csrf_exempt
def player_home(request):
    purchased_gamelist = list()
    purch_gamelist = list()
    current_user = request.user
    userid = get_object_or_404(CustomUser, pk=current_user.id)
    request.session['playerid'] = userid.id # developer id is stored in session for later use
    now = datetime.datetime.now()
    pid = request.GET.get('pid') # purchase id
    ref = request.GET.get('ref') # reference number for each purchase
    result = request.GET.get('result') # result based on succes, cancel, error
    checksum = request.GET.get('checksum') # checksum from payment service
    secret = "0eedc3701a7f6f821b5838e49c20d3d7" # secret token generted using secret id
    # calculating checksum
    checksumstr = "pid={0}&ref={1}&result={2}&token={3}".format(pid, ref, result, secret)
    m = md5(checksumstr.encode("ascii")) # creating the digest of the checksum
    calculated_checksum = m.hexdigest()
    if checksum == calculated_checksum:
        gameid = get_object_or_404(Games, pk=request.session['gameid'])
        gameprice = request.session['gameprice']
        purchase_date = now.strftime("%Y-%m-%d")
        purchase_time = now.strftime("%H:%M")
        try:
            data = Purchase(date_purchased = purchase_date,time_purchased = purchase_time,
                            price_purchased = gameprice, userid = userid, gameid = gameid)
            data1 = Purchase_log(name_of_the_game = gameid.name_of_the_game, price = gameprice, userid = gameid.userid)
            data.save() # storing the information in Purchase table
            data1.save() # storing the information in Purchase_log (used for statistics) table
        except:
            return HttpResponse("Game Already Purchased")

        gamelist = Games.objects.all()
        purchased_game = Purchase.objects.filter(userid=userid)
        for purch in purchased_game:
            purch_gamelist.append(purch.gameid.id)
        for game in gamelist:
            if game.id in purch_gamelist:
                purchased_gamelist.append(game)
        
        # Total number of purchased games
        game_count = len(purchased_gamelist)
        context = {'player_home':"Player Home Page",'gameid':gameid,'gameprice':gameprice,"gamelist":purchased_gamelist,'game_count':game_count,'player_name':userid.username}
        return render(request,'gamestore/player_home.html',context)
    else:
        gamelist = Games.objects.all()
        purchased_game = Purchase.objects.filter(userid=userid)
        for purch in purchased_game:
            purch_gamelist.append(purch.gameid.id)
        for game in gamelist:
            if game.id in purch_gamelist:
                purchased_gamelist.append(game)
        #  Total number of purchased games
        game_count = len(purchased_gamelist)
        context = {'player_home':"Player Home Page","gamelist":purchased_gamelist,'game_count':game_count,'player_name':userid.username}
        return render(request,'gamestore/player_home.html',context)


# This function will be used to upload game by developer
@login_required(login_url='login')
@developer_required
def developer_upload(request):
    now = datetime.datetime.now()
    current_user = request.user
    userid = get_object_or_404(CustomUser, pk=current_user.id)
    name = request.POST.get('name')
    description = request.POST.get('description')
    url = request.POST.get('url')
    category = request.POST.get('category')
    date = now.strftime("%Y-%m-%d")
    time = now.strftime("%H:%M")
    price = request.POST.get('price')
    data = Games(name_of_the_game=name,url_of_the_game=url,price=price,date_added=date,time_added=time,description=description,category=category, userid=userid)
    context = {'upload_game': "Upload New Game"}
    if name is not None and description is not None and url is not None and category is not None and price is not None and date is not None and time is not None:
        data.save() # store information in Game table
        messages.success(request, 'Game is uploaded successfully.')
    return render(request,'gamestore/developer_upload_game.html', context)



# this function will be used for showing sale statistics of the games
@login_required(login_url='login')
@developer_required
def developer_statistics(request):
    current_user = request.user
    profit = 0
    sold_gamelist = Purchase_log.objects.filter(userid = current_user.id).values('name_of_the_game').annotate(total=Sum('price'),counter=Count('name_of_the_game')).order_by('name_of_the_game')
    context = {'dev_home': 'Purchase Statistics', 'gamelist': sold_gamelist}
    return render(request,'gamestore/developer_purchase_statistics.html', context)


# This function will be used for deleting games by developer
@login_required(login_url='login')
@developer_required
def developer_delete_game(request):
    sold_games = list()
    sold_count = 0
    profit = 0
    sold_gamelist = Purchase.objects.all()
    userid = get_object_or_404(CustomUser, pk=request.session['developerid'])
    if request.method == 'POST':
        game_id = request.POST.get('gameid')
        game = Games.objects.get(pk = game_id)
        game.delete() # delete game from the Game database
        gamelist = Games.objects.filter(userid = userid)

        sold_gamelist = Purchase_log.objects.filter(userid = userid)
        # total uploaded game
        game_count = len(gamelist)
        # total number of sold games and profit
        for game in sold_gamelist:
            sold_count += 1
            profit += game.price
        profit = round(profit, 2)
    else:
        gamelist = Games.objects.filter(userid = userid)

        sold_gamelist = Purchase_log.objects.filter(userid = userid)
        # total uploaded game
        game_count = len(gamelist)
        # total number of sold games and profit
        for game in sold_gamelist:
            sold_count += 1
            profit += game.price
        profit = round(profit, 2)
    context = {'dev_home':"Developer Home",'gamelist':gamelist,'game_count':game_count,'profit':profit,'sold_count':sold_count}
    return render(request,'gamestore/developer_home.html',context)


# This function will be triggered when the modify button will be pressed to update the game data.
@login_required(login_url='login')
@developer_required
def developer_update_gameval(request):
    if request.method == 'POST':
        game_id = request.POST.get('gameid')
        request.session['gameid'] = game_id

gamestore/templates/gamestore/developer_home.html
{% extends 'gamestore/developer_layout.html' %}
{% if request.user.is_authenticated %}
{% block left_content %}
    <h1>{{ dev_home }}</h1>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Category</th>
                <th scope="col" colspan="2"></th>
            </tr>
        </thead>
        <tbody>
        {%for game in gamelist%}
            <tr>
                <td style="width: 20%">{{game.name_of_the_game}}</td>
                <td style="width: 50%">{{game.description}}</td>
                <td style="width: 10%">{{game.category}}</td>
                <td>
                    <form action={% url 'gamestore:developer_update_gameval'%} method="post">
                        {% csrf_token %}
                        <input type="hidden" name="gameid" value="{{game.id}}"/>
                        <button type="submit" class="btn btn-success">Modify</button>
                    </form>
                </td>
                <td>
                    <form action={% url 'gamestore:developer_delete_game'%} method="post">
                        {% csrf_token %}
                        <input type="hidden" name="gameid" value="{{game.id}}"/>
                        <button onclick="return confirm('Are you sure you want to delete this?')" type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block right_content %}
    <h3 style="text-align: center;">{{developer_name}}</h3>
    <h3 style="text-align: center;"> Search Games </h3>
    <form style="border: 2px solid #111;" action={% url 'gamestore:developer_home' %} method='post'>
        {% csrf_token %}
        <input style="width: 85%" type="text" placeholder="Search Game.." name="search">
        <button  type="submit" id="faa faa-search"><i class="fa fa-search"></i></button>
    </form>
    <form style="border: 2px solid #111;" action={% url 'gamestore:developer_home' %} method='post'>
        {% csrf_token %}
        <select style="width: 85%" id="category" name="category">
            <option>Select Category</option>
            <option value="thriller">Thriller</option>
            <option value="action">Action</option>
            <option value="sports">Sports</option>
            <option value="strategy">Strategy</option>
            <option value="puzzle">Puzzle</option>
        </select>
        <button type="submit" id="faa faa-search"><i class="fa fa-search"></i></button>
    </form>
    <h3 style="text-align: center;">Statistics</h3>
    <div class="game_stat">
    <table class="table">
        <tbody>
            <tr>
                <td style="width: 60%">Total Uploaded Games</td>
                <td style="width: 40%">{{game_count}}</td>
            </tr>
            <tr>
                <td style="width: 60%">Total Profit</td>
                <td style="width: 40%">{{profit}}</td>
            </tr>
            <tr>
                <td style="width: 60%">Total Sold Games</td>
                <td style="width: 40%">{{sold_count}}</td>
            </tr>
            <tr>
                <td colspan="2">
                    <a href={% url 'gamestore:developer_statistics' %}><button style="width:100%" class="btn btn-success">Statistics</button></a>
                </td>
            </tr>
        </tbody>
    </table>
    </div>
{% endblock %}
{% endif %}

gamestore/templates/gamestore/developer_layout.html
{% extends 'gamestore/base_layout.html' %}
{% block nav %}
    <a class="active" href={% url 'home' %}>
      <button type="button" class="btn btn-primary">Home</button>
    </a>
    <a class="active" href={% url 'gamestore:developer_home' %}>
        <button type="button" class="btn btn-primary">View Games</button>
    </a>
    <a href={% url 'gamestore:developer_upload' %}>
        <button type="button" class="btn btn-primary">Upload Game</button>
    </a>
    <a href={% url 'logout' %} style="float:right;">
        <button type="button" class="btn btn-danger">Logout</button>
    </a>
{% endblock %}

gamestore/templates/gamestore/developer_update_game.html
{% extends 'gamestore/developer_layout.html' %}
{% block left_content %}
    <script>
    document.getElementById('category').value = 'Puzzle';​​​​​​​​​​
    </script>
    <h1>{{ upload_game }}</h1>
    <div class="dev_upload_game">
        <form action={% url 'gamestore:developer_update_game_completed' %} method="post">
        {% csrf_token %}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name Of The Game" value="{{ game.name_of_the_game }}" required>
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" class="form-control" id="description" name="description" placeholder="Description" value="{{ game.description }}" required>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="url" class="form-control" id="url" name="url" placeholder="URL Of The Game" pattern="(http|https)://.*" value="{{ game.url_of_the_game }}" required>
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                <select class="form-control" id="category" name="category" selected="{{ game.category }}" required>
                    <option value="thriller">Thriller</option>
                    <option value="action">Action</option>
                    <option value="sports">Sports</option>
                    <option value="strategy">Strategy</option>
                    <option value="puzzle">Puzzle</option>
                </select>
            </div>
            <div class="form-group">
                <label for="price">Price</label>
                <input type="number" min="0" step='0.01' class="form-control" id="price" name="price" placeholder="Price" value="{{ game.price }}" required>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

gamestore/templates/gamestore/developer_upload_game.html
{% extends 'gamestore/developer_layout.html' %}
{% block left_content %}
    <h1>{{ upload_game }}</h1>
    <div class="dev_upload_game">
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-success">{{message}}</div>
                {% endfor %}
            {% endif %}
        </div>
        <form action={% url 'gamestore:developer_upload' %} method="post">
        {% csrf_token %}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name Of The Game" value="{{ game.name_of_the_game }}" required>
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" class="form-control" id="description" name="description" placeholder="Description" value="{{ game.description }}" required>
            </div>
            <div class="form-group">
                <label for="url">URL</label>
                <input type="url" class="form-control" id="url" name="url" placeholder="URL Of The Game" pattern="(http|https)://.*" value="{{ game.url_of_the_game }}" required>
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                <select class="form-control" id="category" name="category" value="{{ game.category }}" required>
                    <option value="thriller">Thriller</option>
                    <option value="action">Action</option>
                    <option value="sports">Sports</option>
                    <option value="strategy">Strategy</option>
                    <option value="puzzle">Puzzle</option>
                </select>
            </div>
            <div class="form-group">
                <label for="price">Price</label>
                <input type="number" step="0.01" min="0" class="form-control" id="price" name="price" placeholder="Price" value="{{ game.price }}" required>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

gamestore/templates/gamestore/player_available_gamelist.html
{% extends 'gamestore/player_layout.html' %}
{% block left_content %}
    <h1>{{ player_header }}</h1>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Category</th>
                <th scope="col">Price</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
        {%for game in gamelist%}
            <tr>
                <td style="width: 20%">{{game.name_of_the_game}}</td>
                <td style="width: 40%">{{game.description}}</td>
                <td style="width: 10%">{{game.category}}</td>
                <td style="width: 10%">${{game.price}}</td>
                <td>
                    <form action={% url 'gamestore:player_bill_payment' %} method="post">
                        {% csrf_token %}
                        <input type="hidden" name="gameid" value="{{game.id}}"/>
                        <button type="submit" class="btn btn-success">Purchase</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block right_content %}
    <h3> Search Games </h3>
    <form style="border: 2px solid #111;" action={% url 'gamestore:player_available_gamelist' %} method='post'>
        {% csrf_token %}
        <input style="width: 90%" type="text" placeholder="Search Game.." name="search">
        <button type="submit" id="faa faa-search"><i class="fa fa-search"></i></button>
    </form>
    <form style="border: 2px solid #111;" action={% url 'gamestore:player_available_gamelist' %} method='post'>
        {% csrf_token %}
        <select style="width: 90%" id="category" name="category">
            <option>Select Category</option>
            <option value="thriller">Thriller</option>
            <option value="action">Action</option>
            <option value="sports">Sports</option>
            <option value="strategy">Strategy</option>
            <option value="puzzle">Puzzle</option>
        </select>
        <button type="submit" id="faa faa-search"><i class="fa fa-search"></i></button>
    </form>
    
{% endblock %}

gamestore/templates/gamestore/player_gameplay.html
{% extends 'gamestore/player_layout.html' %}
{% block left_content %}
    <h1>{{player_home}}</h1>
    <script>
        var score;
        $(document).ready(function () {
            'use strict';
            $(window).on('message', function (evt) {
                //Get data from sent message
                var data = evt.originalEvent.data;
                var newItem;
                // when submit score is pressed
                if(data.messageType == 'SCORE'){
                    score = data.score;
                    $.ajax({
                    url:'{% url 'gamestore:player_gamescore' %}',
                    type: 'POST',
                    data: {score: score},
                    success:function(json){},
                    complete:function(){},
                    error:function (xhr, textStatus, thrownError){}
                    });
                    var current_score = $('#high').html();
                    if(current_score < score){
                        $("#high").text(score);
                    }
                // when link of the game is clicked, the resolution of the iframe will be changed
                // based on the resolution provided by the game
                }else if(data.messageType == 'SETTING'){
                    newItem = '\n\t<li>' + (data.options.width || '') + '</li>';
                    $('#game_iframe').css('width', data.options.width);
                    $('#game_iframe').css('height', data.options.height);
                }
                // when the save button is pressed
                else if(data.messageType == 'SAVE')
                {
                    $.ajax({
                    url:'{% url 'gamestore:player_gamestate' %}',
                    type: 'POST',
                    data: {state: JSON.stringify(data),score:data.gameState.score},
                    success:function(json){},
                    complete:function(){},
                    error:function (xhr, textStatus, thrownError){}
                    });
                    var current_score = $('#high').html();
                    if(current_score < data.gameState.score){
                        $("#high").text(data.gameState.score);
                    }

                }
                // when the load button is pressed
                // If the previous state of the game is stored then the messageType will be LOAD
                // messageType will be ERROR if there is no previous state stored
                else if(data.messageType == 'LOAD_REQUEST')
                {
                    $.ajax({
                    url:'{% url 'gamestore:player_gameload' %}',
                    type: 'GET',
                    datatype:'json',
                    success:function(json){

                        if(json.value)
                        {
                            var obj_savestate = JSON.parse(json.value);
                            obj_savestate.messageType = 'LOAD'

                            var iframeEl = document.getElementById('game_iframe');
                            iframeEl.contentWindow.postMessage(obj_savestate, '*');
                        }
                        else{
                            var error_message = {
                            messageType: "ERROR",
                            info: "Gamestate could not be loaded"
                            };
                            var iframeE2 = document.getElementById('game_iframe');
                            iframeE2.contentWindow.postMessage(error_message, '*');
                        }
                    },
                    complete:function(){},
                    error:function (xhr, textStatus, thrownError){}
                    });
                }
                $('#actions').prepend(newItem);
            });
        });
    </script>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Attribute</th>
                <th scope="col">Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="width: 20%">Name</td>
                <td style="width: 60%">{{game.name_of_the_game}}</td>
            </tr>
            <tr>
                <td style="width: 20%">Description</td>
                <td style="width: 60%">{{game.description}}</td>
            </tr>
            <tr>
                <td style="width: 20%">URL</td>
                <td style="width: 60%"><a href={{game.url_of_the_game}} target="iframe_a">{{game.url_of_the_game}}</td>
            </tr>
        </tbody>
    </table>
    <div>
        <iframe id='game_iframe' width=100px height=100px name="iframe_a" >
        </iframe>
    </div>

{% endblock %}

{% block right_content %}
    <h3 style="text-align: center;">Statistics</h3>
    <div class="game_stat">
        <div id="high_score">
            <table class="table">
                <tbody>
                    <tr>
                        <td style="width: 60%">Highest Score (Global)</td>
                        <td id="high" style="width: 40%">{{highest_score}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

gamestore/templates/gamestore/player_layout.html
{% extends 'gamestore/base_layout.html' %}
{% block nav %}
    <a class="active" href={% url 'home' %}>
      <button type="button" class="btn btn-primary">Home</button>
    </a>
    <a href={% url 'gamestore:player_home' %}>
        <button type="button" class="btn btn-primary">View Games</button>
    </a>
    <a href={% url 'gamestore:player_available_gamelist' %}>
        <button type="button" class="btn btn-primary">Purchase Games</button>
    </a>
    <a href={% url 'logout' %} style="float:right;">
        <button type="button" class="btn btn-danger">Logout</button>
    </a>
{% endblock %}